site_name: ГАИ — Amazing Online
site_url: https://trapkamku-create.github.io/goss-docs/
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Переключить на тёмную тему
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
  - Главная: index.md
